backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'static/uploads'
public_folder: '/uploads'
site_url: https://vue-netlifycms.netlify.com/
collections:
  - label: 'Products'
    name: 'products'
    folder: 'content/products'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Description', name: 'description', widget: 'markdown' }
